// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ea30ebe3-0c0b-448b-a103-dc1257e51293",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FpvfcApGw",
    "aws_user_pools_web_client_id": "2g2la3g0hl5sgluekhc7mknsnc",
    "oauth": {
        "domain": "ppe-reuze-reuze.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://reuze.covid.tools/signedin/",
        "redirectSignOut": "https://reuze.covid.tools/signedout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://a7nnvjgdvzfihcgoogbef46gx4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mqivgovqpvgjbnmnuljssmbidq"
};


export default awsmobile;
